var frasi = [
    "C'è un solo modo di risolvere un problema: affrontarlo",
    "Perdonare è da cristiani, dimenticare da stupidi",
    "Togliere le macchie appena possibile, il risultato è sempre migliore",
    "Anche gli asini lavorano",
    "Credi ma non scommettere",
    "Non sfregare le macchie, tamponale",
    "Credi sempre ma controlla sempre",
    "Tutto può tornare utile, anche le unghie per sbucciare l&amp;aglio",
    "Quello che vuoi fallo, quello che non vuoi demandalo",
    "Tutti hanno un loro credo",
    "Un leggero appretto facilita la stiratura",
    "Le grandi spese si programmano, le piccole ti rendono povero",
    "Si ha più successo con la sfacciataggine che con un portafoglio pieno",
    "Si sa come si nasce ma non come si muore",
    "Il cotone si stira umido, la lana asciutta",
    "Un bel tacer non fu mai detto",
    "Carta canta e villan dorme",
    "Le tarme mangiano più volentieri le parti sporche",
    "Se parli, dì la verità, ma non sempre è il caso di parlare",
    "Occhio non vede, cuore non duole",
    "Provare sempre gli smacchiatori in una zona nascosta dell&amp;indumento",
    "Meglio un avversario intelligente che un socio stupido",
    "Chi dorme non piglia pesci",
    "Prevenire è meglio che...smacchiare",
    "L'uomo propone ma il Signore dispone",
    "Il diavolo fa le pentole ma non i coperchi",
    "Tra il dire ed il fare c&amp;è; di mezzo il mare",
    "Leggi le etichette",
    "Solo le forbici tolgono tutte le macchie",
    "L'occhio del padrone ingrassa il cavallo",
    "Via il gatto, i topi ballano",
    "Sporco o macchiato?",
    "Tanto va la gatta al lardo che ci lascia lo zampino",
    "Si sa come si nasce ma non come si muore",
    "Di notte tutti i gatti sono grigi",
    "Una rondine non fa primavera",
    "Le tarme mangiano le parti sporche",
    "L'abito non fa il monaco",
    "Se ti danno un euro per cinquanta centesimi, è un inganno",
    "Un bucato ben steso si stira meglio",
    "La vita è fatta anche di piccoli piaceri",
    "La pelle bagnata sempre lontana dal calore",
    "Ognuno faccia il proprio lavoro",
    "Per comandare bisogna saper ubbidire",
    "Candeggina e perborato non vanno assieme",
    "Non è tutto oro quello che luccica",
    "A volte, il meglio è nemico del bene",
    "Comincia col provare la soluzione più semplice",
    "I bottoni belli, è meglio toglierli",
    "Il primo guadagno è il risparmio"
]
var d = new Date();
var day = d.getDate() + d.getDay() + d.getMonth();
document.write(frasi[day-1]);
